language: python
python:
- '3.6'
before_install:
- openssl aes-256-cbc -K $encrypted_92a5d2eda6d4_key -iv $encrypted_92a5d2eda6d4_iv
  -in aws_interface/secret.tar.enc -out aws_interface/secret.tar -d
- cd aws_interface
- tar -xvf secret.tar
- cd ..
install:
- pip install -r aws_interface/requirements.txt
script:
- python aws_interface/manage.py makemigrations
- python aws_interface/manage.py migrate
- python aws_interface/manage.py test
